<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2023 DV Bern AG, Switzerland
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as
  ~ published by the Free Software Foundation, either version 3 of the
  ~ License, or (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program. If not, see <https://www.gnu.org/licenses />.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>parent</artifactId>
        <groupId>ch.dvbern.oss.maven</groupId>
        <version>3.0.5</version>
    </parent>

    <groupId>ch.dvbern.ebegu</groupId>
    <artifactId>ebegu</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>eBEGU - Multimodule Project</name>

    <properties>
        <revision>2023-SNAPSHOT</revision>

        <maven-enforcer-plugin.version>3.4.1</maven-enforcer-plugin.version>

        <dvb.git.serverId>gitlab.dvbern.ch</dvb.git.serverId>

        <!-- Wird ggf. im Profil "development-mode' ueberschrieben -->
        <skip-code-validation>false</skip-code-validation>

        <!-- local database properties -->
        <database.jdbc.driver>org.mariadb.jdbc.Driver</database.jdbc.driver>
        <database.jdbc.url>jdbc:mariadb://localhost/ebegu</database.jdbc.url>
        <database.jdbc.usr>ebegu</database.jdbc.usr>
        <database.jdbc.pwd>ebegu</database.jdbc.pwd>

        <!-- keep in sync with dependencies from Wildfly BOM -->
        <version.hibernate>6.4.4.Final</version.hibernate>
        <version.hibernate-search>7.1.0.Final</version.hibernate-search>

        <version.flyway>9.16.0</version.flyway>
        <version.mysqldriver>3.1.2</version.mysqldriver>
        <version.wildfly.container>33.0.2.Final</version.wildfly.container>
        <version.bouncycastle>1.70</version.bouncycastle>
        <version.jackson>2.12.7.20221012</version.jackson>
        <version.hamcrest>2.2</version.hamcrest>
        <version.poi>5.2.3</version.poi>
        <version.iso20022>7.0.2</version.iso20022>
        <version.jakarata-xml>2.3.3</version.jakarata-xml>
        <version.jaxb-runtime>2.3.5</version.jaxb-runtime>
        <version.junit5>5.9.2</version.junit5>
        <ebegu-code-conventions.version>1.0.3</ebegu-code-conventions.version>
        <version.openpdf>1.3.30</version.openpdf>
        <maven-pmd-plugin.version>3.27.0</maven-pmd-plugin.version>
        <spotbugs-maven-plugin.version>4.9.8.3</spotbugs-maven-plugin.version>
        <spotbugs-annotations.version>4.9.8</spotbugs-annotations.version>
        <lombok.version>1.18.32</lombok.version>
        <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/../ebegu-server/target/site/jacoco-aggregate/jacoco.xml,${project.basedir}/../ebegu-testutils/target/site/jacoco-aggregate/jacoco.xml,${project.basedir}/../ebegu-rest/target/site/jacoco-aggregate/jacoco.xml,${project.basedir}/../ebegu-external-api/target/site/jacoco-aggregate/jacoco.xml,${project.basedir}/../ebegu-dbschema/target/site/jacoco-aggregate/jacoco.xml,${project.basedir}/../ebegu-ws/target/site/jacoco-aggregate/jacoco.xml,${project.basedir}/../ebegu-shared/target/site/jacoco-aggregate/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <maven-compiler-plugin.source>17</maven-compiler-plugin.source>
        <maven-compiler-plugin.target>17</maven-compiler-plugin.target>
        <keycloak-admin-client.version>26.0.7</keycloak-admin-client.version>
        <argLine/> <!-- Do not remove or surefire plugin will break if coverage profile is not enabled -->
    </properties>

    <licenses>
        <license>
            <name>GNU Affero General Public License</name>
            <url>http://www.gnu.org/licenses/agpl-3.0.txt</url>
        </license>
    </licenses>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.wildfly.bom</groupId>
                <artifactId>wildfly-microprofile</artifactId>
                <version>${version.wildfly.container}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.wildfly.bom</groupId>
                <artifactId>wildfly-ee-with-tools</artifactId>
                <version>${version.wildfly.container}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${version.junit5}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.batch</groupId>
                <artifactId>jakarta.batch-api</artifactId>
                <version>2.1.1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wildfly</groupId>
                <artifactId>wildfly-batch-jberet</artifactId>
                <version>${version.wildfly.container}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.el</groupId>
                <artifactId>jakarta.el-api</artifactId>
                <version>6.0.1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.glassfish.expressly</groupId>
                <artifactId>expressly</artifactId>
                <version>5.0.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>3.0.2</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>6.0.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.ejb</groupId>
                <artifactId>jakarta.ejb-api</artifactId>
                <version>4.0.1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.security.enterprise</groupId>
                <artifactId>jakarta.security.enterprise-api</artifactId>
                <version>3.0.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.glassfish.soteria</groupId>
                <artifactId>jakarta.security.enterprise</artifactId>
                <version>3.0.3</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wildfly.security.jakarta</groupId>
                <artifactId>jakarta-security</artifactId>
                <version>3.0.3.Final</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.authentication</groupId>
                <artifactId>jakarta.authentication-api</artifactId>
                <version>3.0.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>jackson-module-jsonSchema-jakarta</artifactId>
                <version>2.17.0</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>2.16.1</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jdk8</artifactId>
                <version>2.15.4</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.hibernate.search</groupId>
                <artifactId>hibernate-search-backend-elasticsearch</artifactId>
                <version>${version.hibernate-search}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.hibernate.search</groupId>
                <artifactId>hibernate-search-mapper-orm</artifactId>
                <version>${version.hibernate-search}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.hibernate.search</groupId>
                <artifactId>hibernate-search-mapper-orm-jakarta-batch-jberet</artifactId>
                <version>${version.hibernate-search}</version>
            </dependency>

            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-admin-client</artifactId>
                <version>${keycloak-admin-client.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.threeten-jaxb</groupId>
                <artifactId>threeten-jaxb-core</artifactId>
                <version>2.2.0</version>
            </dependency>
            <!-- region other libs -->
            <dependency>
                <groupId>com.ibm.icu</groupId>
                <artifactId>icu4j</artifactId>
                <version>74.2</version>
            </dependency>
            <dependency>
                <groupId>com.ibm.icu</groupId>
                <artifactId>icu4j-charset</artifactId>
                <version>75.1</version>
            </dependency>

            <dependency>
                <groupId>com.google.code.findbugs</groupId>
                <artifactId>annotations</artifactId>
                <version>3.0.1u2</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.findbugs</groupId>
                <artifactId>jsr305</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-annotations</artifactId>
                <version>${spotbugs-annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>31.1-jre</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${version.poi}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${version.poi}</version>
            </dependency>
            <dependency>
                <groupId>org.mariadb.jdbc</groupId>
                <artifactId>mariadb-java-client</artifactId>
                <version>${version.mysqldriver}</version>
            </dependency>
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-core</artifactId>
                <version>${version.flyway}</version>
            </dependency>
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-mysql</artifactId>
                <version>${version.flyway}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>1.27</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-email2-jakarta</artifactId>
                <version>2.0.0-M1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.12.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpasyncclient</artifactId>
                <version>4.1.5</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>commons-configuration</groupId>
                <artifactId>commons-configuration</artifactId>
                <version>1.10</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.11.0</version>
            </dependency>
            <dependency>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
                <version>1.2</version>
            </dependency>
            <dependency>
                <groupId>commons-lang</groupId>
                <artifactId>commons-lang</artifactId>
                <version>2.6</version>
            </dependency>
            <dependency>
                <groupId>commons-collections</groupId>
                <artifactId>commons-collections</artifactId>
                <version>3.2.2</version>
            </dependency>
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>1.15</version>
            </dependency>
            <dependency>
                <groupId>commons-net</groupId>
                <artifactId>commons-net</artifactId>
                <version>3.9.0</version>
            </dependency>
            <dependency>
                <groupId>net.bull.javamelody</groupId>
                <artifactId>javamelody-core</artifactId>
                <version>2.2.0</version>
            </dependency>
            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>2.3.18</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>24.0.0</version>
                <!-- soll nur von der IDE genutzt werden -->
                <scope>provided</scope>
                <optional>true</optional>
            </dependency>
            <dependency>
                <groupId>com.codebullets.stateless4j</groupId>
                <artifactId>stateless4j</artifactId>
                <version>3.1.1</version>
            </dependency>
            <dependency>
                <artifactId>openpdf</artifactId>
                <groupId>com.github.librepdf</groupId>
                <version>${version.openpdf}</version>
            </dependency>
            <dependency>
                <groupId>ch.dvbern.kibon</groupId>
                <artifactId>kibon-exchange-api-commons</artifactId>
                <version>6.2.5</version>
            </dependency>
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>3.9.1</version>
            </dependency>
            <dependency>
                <groupId>io.confluent</groupId>
                <artifactId>kafka-avro-serializer</artifactId>
                <version>5.5.15</version>
            </dependency>
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>1.11.3</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>1.22</version>
            </dependency>

            <!-- endregion -->


            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-ext</artifactId>
                <version>2.0.11</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>log4j-over-slf4j</artifactId>
                <version>2.0.11</version>
            </dependency>

            <!-- region DV Bern Libs -->
            <dependency>
                <groupId>ch.dvbern.oss.datehelper</groupId>
                <artifactId>date-helper</artifactId>
                <version>1.2.0</version>
            </dependency>
            <dependency>
                <groupId>ch.dvbern.oss.beanvalidation</groupId>
                <artifactId>beanvalidation</artifactId>
                <version>1.1.0</version>
            </dependency>
            <dependency>
                <groupId>ch.dvbern.oss.iso20022</groupId>
                <artifactId>iso20022-ch-impl</artifactId>
                <version>${version.iso20022}</version>
                <exclusions>
                    <!-- don't load JavaEE7 stuff, or we will have class loading issues -->
                    <exclusion>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.validation</groupId>
                        <artifactId>validation-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>ch.dvbern.oss.excelmerger</groupId>
                <artifactId>excelmerger-impl</artifactId>
                <version>4.7.0</version>
            </dependency>
            <dependency>
                <groupId>ch.dvbern.oss.invoicegenerator</groupId>
                <artifactId>invoice-generator</artifactId>
                <version>6.1.2</version>
            </dependency>
            <dependency>
                <groupId>ch.dvbern.oss.healthcheck.gc</groupId>
                <artifactId>gc-health-check</artifactId>
                <version>1.0.1</version>
            </dependency>
            <!-- endregion -->

            <!-- region testing -->
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <scope>test</scope>
                <version>4.13.2</version>
            </dependency>
            <dependency>
                <groupId>org.easymock</groupId>
                <artifactId>easymock</artifactId>
                <version>5.2.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>io.github.origin-energy</groupId>
                <artifactId>java-snapshot-testing-junit5</artifactId>
                <version>4.0.8</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>io.github.origin-energy</groupId>
                <artifactId>java-snapshot-testing-plugin-jackson</artifactId>
                <version>4.0.8</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest</artifactId>
                <version>${version.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-library</artifactId>
                <version>${version.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-core</artifactId>
                <version>${version.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>eu.codearte.catch-exception</groupId>
                <artifactId>catch-exception</artifactId>
                <version>2.0</version>
                <scope>test</scope>
            </dependency>
            <!-- endregion -->

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib-jdk8</artifactId>
                <version>1.8.0</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib-common</artifactId>
                <version>1.8.0</version>
            </dependency>

        </dependencies>

    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-ext</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </dependency>

        <!-- region testing -->
        <dependency>
            <!-- this is needed or IntelliJ gives junit.jar or junit-platform-launcher:1.3.2 not found errors -->
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- region Hamcrest -->
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-library</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.npathai</groupId>
            <artifactId>hamcrest-optional</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.spotify</groupId>
            <artifactId>hamcrest-jackson</artifactId>
            <version>1.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.spotify</groupId>
            <artifactId>hamcrest-pojo</artifactId>
            <version>1.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>eu.codearte.catch-exception</groupId>
            <artifactId>catch-exception</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- endregion -->

    </dependencies>

    <profiles>
		<profile>
            <id>sentry-source-maps</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.sentry</groupId>
                        <artifactId>sentry-maven-plugin</artifactId>
                        <version>0.0.4</version>
                        <configuration>
                            <debugSentryCli>true</debugSentryCli>
                            <org>kibon</org>
                            <project>kibon-backend</project>
                            <url>https://sentry.dvbern.ch</url>
                            <authToken>${env.SENTRY_AUTH_TOKEN}</authToken>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>uploadSourceBundle</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>development-mode</id>
            <activation>
                <property>
                    <name>skipTests</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <spotless.check.skip>true</spotless.check.skip>
                <skip-code-validation>true</skip-code-validation>
                <maven.javadoc.skip>true</maven.javadoc.skip>
            </properties>
        </profile>

        <profile>
            <id>coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.12</version>
                        <configuration>
                            <includeCurrentProject>true</includeCurrentProject>
                        </configuration>
                        <executions>
                            <execution>
                                <id>prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <sourcepath>target/generated-sources/delombok</sourcepath>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.5.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    <flattenDependencyMode>all</flattenDependencyMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <excludedGroups>${surefire.excludedGroups}</excludedGroups>
                    <redirectTestOutputToFile>false</redirectTestOutputToFile>
                    <!--port offset fuer embedded wildfly -->
                    <argLine>
                        @{argLine}
                        -Djboss.socket.binding.port-offset=10000
                    </argLine>
                    <systemPropertyVariables>
                        <!-- because many services log on INFO, we increase the default log level for unit tests -->
                        <org.slf4j.simpleLogger.defaultLogLevel>WARN</org.slf4j.simpleLogger.defaultLogLevel>
                    </systemPropertyVariables>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <!-- Nur Deployen wenn alle Module erfolgreich gebaut wurden -->
                    <deployAtEnd>true</deployAtEnd>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>2.43.0</version>
                    <configuration>
                        <java>
                            <eclipse>
                                <file>${maven.multiModuleProjectDirectory}/DVB_2022_08_19_Conventions-eclipse.xml</file>
                            </eclipse>
                            <removeUnusedImports />
                            <importOrder>
                                <!-- '\#' selects static imports -->
                                <order>java,javax|jakarta,,\#</order>
                            </importOrder>
                        </java>
                    </configuration>
					<executions>
						<execution>
							<goals>
								<goal>check</goal>
							</goals>
						</execution>
					</executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <configuration>
                        <includeTestResources>true</includeTestResources>
                        <configLocation>checkstyle-configuration.xml</configLocation>
                        <violationSeverity>error</violationSeverity>
                        <suppressionsLocation>checkstyle-suppressions.xml</suppressionsLocation>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-pmd-plugin</artifactId>
                    <version>${maven-pmd-plugin.version}</version>
                    <configuration>
                        <printFailingErrors>true</printFailingErrors>
                        <rulesets>
                            <ruleset>rules/pmd/pmd-rules.xml</ruleset>
                        </rulesets>
                        <printFailingErrors>true</printFailingErrors>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <!-- von parent-pom ueberschrieben, siehe KIBON-1703 -->
                    <version>${spotbugs-maven-plugin.version}</version>
                    <configuration>
                        <includeFilterFile>rules/findbugs/findbugs-includes.xml</includeFilterFile>
                        <excludeFilterFiles>
                            <excludeFilterFile>rules/findbugs/findbugs-excludes.xml</excludeFilterFile>
                            <excludeFilterFile>${maven.multiModuleProjectDirectory}/spotbugs-exclude.xml</excludeFilterFile>
                        </excludeFilterFiles>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.flywaydb</groupId>
                    <artifactId>flyway-maven-plugin</artifactId>
                    <version>${version.flyway}</version>
                </plugin>

                <plugin>
                    <groupId>de.juplo</groupId>
                    <artifactId>hibernate-maven-plugin</artifactId>
                    <version>2.2.0</version>
                </plugin>

                <plugin>
                    <groupId>fr.jcgay.maven.plugins</groupId>
                    <artifactId>buildplan-maven-plugin</artifactId>
                    <version>1.5</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>check-maven-setup</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <fail>false</fail>
                                <failFast>true</failFast>
                                <rules>
                                    <dependencyConvergence/>
                                    <reactorModuleConvergence/>
                                    <requireJavaVersion>
                                        <!-- Bei aelteren Versionen aendern die Unit-Test-Ergebnisse bei Berechnungen mit BigDecimal -->
                                        <version>[1.8.0-40,)</version>
                                    </requireJavaVersion>
                                    <requireMavenVersion>
                                        <version>3.5.4</version>
                                    </requireMavenVersion>
                                    <!-- Pruefen, dass im Release keine SNAPSHOT-Dependencies mehr drin sind -->
                                    <requireReleaseDeps>
                                        <failWhenParentIsSnapshot>true</failWhenParentIsSnapshot>
                                        <onlyWhenRelease>true</onlyWhenRelease>
                                        <searchTransitive>true</searchTransitive>
                                    </requireReleaseDeps>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>9.2.0</version>
                    <configuration>
                        <failBuildOnAnyVulnerability>true</failBuildOnAnyVulnerability>
                        <bundleAuditAnalyzerEnabled>false</bundleAuditAnalyzerEnabled>
                        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        <suppressionFile>dependency-check-suppressions.xml</suppressionFile>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>ebegu-dbschema</module>
        <module>ebegu-shared</module>
        <module>ebegu-server</module>
        <module>ebegu-testutils</module>
        <module>ebegu-rest</module>
        <module>ebegu-external-api</module>
        <module>ebegu-ws</module>
        <module>ebegu-auth</module>
    </modules>

</project>
