export enum GemeindeKennzahlenBatchjobResult {
    SUCCESS = 'SUCCESS',
    FAILURE = 'FAILURE',
    CREATED_REMINDER_NOT_SENT = 'CREATED_REMINDER_NOT_SENT',
    REMINDER_NOT_ACTIVATED = 'REMINDER_NOT_ACTIVATED',
    NOT_ACTIVATED = 'NOT_ACTIVATED'
}
