<?xml version="1.0" encoding="UTF-8"?>
<!-- DV Bern AG (MOAM), 19.11.2021: Initialversion -->
<!-- DV Bern AG (MOAM), 26.11.2021: GetSteuerdaten und GetSteuerdatenResponse -->
<xs:schema xmlns:tns="http://sv.fin.be.ch/schemas/NESKOVANP/20211119/KiBonAnfrageService"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           targetNamespace="http://sv.fin.be.ch/schemas/NESKOVANP/20211119/KiBonAnfrageService">

    <!--Request-->
    <xs:complexType name="GetSteuerdaten">
        <xs:sequence>
            <!--  ZPVNr und Sozialversicherungsnummer optional in schema definition, muss mind. 1 gegeben logic check in code.  -->
            <xs:element minOccurs="0" name="ZPVNr">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> ZPV-Nummer des Antragstellers (obligatorisch). Der Antragsteller darf der Vorstand oder der Partner sein. </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minExclusive value="0"/>
                        <xs:maxInclusive value="999999999"/>
                        <!--  9-stellig  -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="Sozialversicherungsnummer">
                <xs:annotation>
                    <xs:documentation> Sozialversicherungsnummer muss vorhanden sein, wenn ZPV-Nummer fehlt </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minExclusive value="0"/>
                        <xs:maxInclusive value="9999999999999"/>
                        <!--  13-stellig  -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Geburtsdatum" type="xs:date">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Geburtsdatum des Antragstellers (obligatorisch). Gültige Wertbereiche: 01.01.1900 - aktuelles Tagesdatum. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="KiBonAntragID" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Antrag-ID von von KiBon (obligatorisch). Die Antrag-ID ist eine UUID. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="BeginnGesuchsperiode">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Beginn Gesuchsperiode (obligatorisch). Gültige Wertbereiche: 2019 - 9999. </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:pattern value="[2-9][0-9][0-9][0-9]"/>
                        <!--  nur 4-stellig  -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CodeVeranlagungsstand">
        <xs:annotation>
            <xs:documentation xml:lang="de"> Code Stand der Veranlagung. Mögliche Werte sind: offen (1) / provisorisch (2) / rechtskräftig (3). </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="OFFEN">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Offen (keine Daten) (1) </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="PROVISORISCH">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Provisorisch (2) </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="RECHTSKRAEFTIG">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Rechtskräftig (3) </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <!-- Response -->
    <xs:complexType name="GetSteuerdatenResponse">
        <xs:sequence>
            <xs:element maxOccurs="1" name="SteuerDatenResponse" type="tns:SteuerDatenResponseType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SteuerDatenResponseType">
        <xs:sequence>
            <xs:element name="ZPVNrAntragsteller" type="xs:int">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> ZPV-Nummer des Antragstellers gemäss Request-Attribut ZPVNr (s. GetSteuerdaten Request) </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="SozialversicherungsNrAntragsteller" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Sozialversicherung-Nummer des Antragstellers gemäss Request-Attribut ZPVNr (s. GetSteuerdaten Request) </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeburtsdatumAntragsteller" type="xs:date">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Geburtsdatum des Antragstellers gemäss Request-Attribut Geburtsdatum (s. GetSteuerdaten Request). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="KiBonAntragID" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Antrag-ID von von KiBon gemäss Request-Attribut KiBonAntragID (s. GetSteuerdaten Request). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="BeginnGesuchsperiode" type="xs:int">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Beginn Gesuchsperiode gemäss Request-Attribut BeginnGesuchsperiode (s. GetSteuerdaten Request) </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="ZPVNrDossiertraeger" type="xs:int">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> ZPV-Nummer des Dossierträgers (dessen Steuerfall ermittelt wurde). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="SozialversicherungsNrDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Sozialversicherung-Nummer des Dossierträgers (dessen Steuerfall ermittelt wurde). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeburtsdatumDossiertraeger" type="xs:date">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Geburtsdatum des Dossierträgers (dessen Steuerfall ermittelt wurde). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="ZPVNrPartner" type="xs:int">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> ZPV-Nummer des Partners vom Dossierträger (dessen Steuerfall ermittelt wurde). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="SozialversicherungsNrPartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Sozialversicherung-Nummer des Partners vom Dossierträger (dessen Steuerfall ermittelt wurde). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="GeburtsdatumPartner" type="xs:date">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Geburtsdatum des Partners vom Dossierträger (dessen Steuerfall ermittelt wurde). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="FallId" type="xs:int">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Fall-ID des ermittelten Steuerfalls. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Antwortdatum" type="xs:date">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Datum der Antwort, welches das aktuelle Datum ist. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="SynchroneAntwort" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ist true, wenn die Aufbereitung der Antwort Online, d.h. aus dem Webservice erfolgt, sonst false </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Veranlagungsstand" type="tns:CodeVeranlagungsstand">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Code Stand der Veranlagung. Mögliche Werte sind: offen (1) / provisorisch (2) / rechtskräftig (3). </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="UnterjaehrigerFall" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ist true, wenn es sich beim zu pruefenden Fall oder den allenfalls einbezogenen Vorperiodenfällen nicht um einen Fall mit ganzjaehriger Veranlagung vom 01.01. bis 31.12. handelt. Dies führt dann dazu, dass keine Veranlagungsdaten zu Einkommen und Vermögen übertragen werden. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="UnregelmaessigkeitInDerVeranlagung" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ist true, wenn es sich nicht um eine Standard-Deklaration handelt. Falls aus den beiden Vorjahren Geschaeftsertraege resultieren, werden diese in die Ermittlung des Flags ebenfalls einbezogen. Dies führt dann dazu, dass keine Veranlagungsdaten zu Einkommen und Vermögen übertragen werden. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="VeraendertePartnerschaft" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ist true, wenn es über die Zeitspanne der beiden Vorperioden eine Veränderung der Haushalt-beteiligten Partner gab (Heirat / Trennung) gemaess VANP Register. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="ErwerbseinkommenUnselbstaendigkeitDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Einkommen aus unselbständiger Erwerbstätigkeit des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="ErwerbseinkommenUnselbstaendigkeitPartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Einkommen aus unselbständiger Erwerbstätigkeit des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="SteuerpflichtigesErsatzeinkommenDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Steuerpflichtiges Ersatzeinkommen des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="SteuerpflichtigesErsatzeinkommenPartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Steuerpflichtiges Ersatzeinkommen des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="ErhalteneUnterhaltsbeitraegeDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Erhaltene Unterhaltsbeiträge des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="ErhalteneUnterhaltsbeitraegePartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Erhaltene Unterhaltsbeiträge des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="AusgewiesenerGeschaeftsertragDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ausgewiesener Geschäftsertrag (aktuelles jahr) des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="AusgewiesenerGeschaeftsertragPartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ausgewiesener Geschäftsertrag (aktuelles jahr) des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="AusgewiesenerGeschaeftsertragVorperiodeDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ausgewiesener Geschäftsertrag Vorperiode (Jahr - 1) des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="AusgewiesenerGeschaeftsertragVorperiodePartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ausgewiesener Geschäftsertrag Vorperiode (Jahr - 1) des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="AusgewiesenerGeschaeftsertragVorperiode2Dossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ausgewiesener Geschäftsertrag Vorvorperiode (Jahr - 2) des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="AusgewiesenerGeschaeftsertragVorperiode2Partner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Ausgewiesener Geschäftsertrag Vorvorperiode (Jahr - 2) des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="WeitereSteuerbareEinkuenfteDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Weitere steuerbare Einkünfte des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="WeitereSteuerbareEinkuenftePartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Weitere steuerbare Einkünfte des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="BruttoertraegeAusVermoegenOhneLiegenschaftenUndOhneEGME" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Bruttoertraege aus beweglichem Vermoegen ohne Liegenschaften und ohne Erbengemeinschaften oder Miteigentum </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="BruttoertraegeAusLiegenschaften" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Bruttoertraege aus unbeweglichem Vermoegen (Liegenschaften) </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="NettoertraegeAusEGMEDossiertraeger" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Nettoertraege aus Erbengemeinschaften oder Miteigentum des Dossiertraegers </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="NettoertraegeAusEGMEPartner" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Nettoertraege aus Erbengemeinschaften oder Miteigentum des Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="GeleisteteUnterhaltsbeitraege" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Geleistete Unterhaltsbeiträge (= Abzug fuer bezahlte Alimente) </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="Schuldzinsen" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Schuldzinsen des Dossiertraegers und/oder Partners </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="GewinnungskostenBeweglichesVermoegen" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Kosten fuer Wertschriften und Lotteriegewinn-Einsaetze </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="LiegenschaftsAbzuege" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Gewinnungskosten fuer unbewegliches Vermoegen </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="Nettovermoegen" type="xs:long">
                <xs:annotation>
                    <xs:documentation xml:lang="de"> Bruttovermögen abzgl. Schulden ohne Berücksichtigung von Repartitionsfaktoren </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="GetSteuerdaten" type="tns:GetSteuerdaten"/>
    <xs:element name="GetSteuerdatenResponse" type="tns:GetSteuerdatenResponse"/>
</xs:schema>
