<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2023 DV Bern AG, Switzerland
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as
  ~ published by the Free Software Foundation, either version 3 of the
  ~ License, or (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program. If not, see <https://www.gnu.org/licenses />.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ebegu</artifactId>
        <groupId>ch.dvbern.ebegu</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ebegu-server</artifactId>

    <dependencies>
        <!--region WildFly stack -->
        <dependency>
            <!-- Fuer DB-Skripts (TransactionTimeout) -->
            <groupId>org.jboss.ejb3</groupId>
            <artifactId>jboss-ejb3-ext-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>dom4j</groupId>
                    <artifactId>dom4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-envers</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.search</groupId>
            <artifactId>hibernate-search-engine</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.hibernate.search</groupId>
            <artifactId>hibernate-search-mapper-orm-jakarta-batch-jberet</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hibernate.search</groupId>
            <artifactId>hibernate-search-mapper-orm</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.batch</groupId>
            <artifactId>jakarta.batch-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-batch-jberet</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.el</groupId>
            <artifactId>jakarta.el-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.expressly</groupId>
            <artifactId>expressly</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.microprofile.config</groupId>
            <artifactId>microprofile-config-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.security.enterprise</groupId>
            <artifactId>jakarta.security.enterprise-api</artifactId>
        </dependency>
        <!-- endregion -->

        <!-- region submodules -->
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-shared</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-auth</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-testutils</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-ws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- endregion -->
        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.ibm.icu</groupId>
            <artifactId>icu4j</artifactId>
        </dependency>

        <!-- region DV Bern libs -->
        <dependency>
            <groupId>jakarta.ejb</groupId>
            <artifactId>jakarta.ejb-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.oss.iso20022</groupId>
            <artifactId>iso20022-ch-impl</artifactId>
        </dependency>
        <!-- endregion -->

        <!-- region testing -->
        <dependency>
            <groupId>io.github.origin-energy</groupId>
            <artifactId>java-snapshot-testing-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.origin-energy</groupId>
            <artifactId>java-snapshot-testing-plugin-jackson</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.easymock</groupId>
            <artifactId>easymock</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.el</artifactId>
            <version>3.0.3</version>
            <scope>test</scope>
        </dependency>
        <!-- endregion -->

        <!-- region Mailing -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-email2-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
        </dependency>
        <!-- endregion -->

        <dependency>
            <groupId>org.hibernate.search</groupId>
            <artifactId>hibernate-search-backend-elasticsearch</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.search</groupId>
            <artifactId>hibernate-search-backend-lucene</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.kibon</groupId>
            <artifactId>kibon-exchange-api-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-avro-serializer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.11</version>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-admin-client</artifactId>
        </dependency>
    </dependencies>


    <profiles>

        <profile>
            <!-- Schema Generation-->
            <id>generate-ddl</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>de.juplo</groupId>
                        <artifactId>hibernate-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>create</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <force>true</force>

                            <username>${database.jdbc.usr}</username>
                            <password>${database.jdbc.pwd}</password>
                            <driver>${database.jdbc.driver}</driver>
                            <url>${database.jdbc.url}</url>

                            <!--Der verwendete Dialekt fuer die Schema generierung-->
                            <dialect>org.hibernate.dialect.MariaDBDialect</dialect>
                            <!-- Optionale Namensgebungsstrategie. Hiermit koennen die Tabellennamen zum Beispiel mit -->
                            <!-- underscore generiert werden statt mit CamelCase (application-property statt ApplicationProperty) -->
                            <physicalNamingStrategy>ch.dvbern.ebegu.persistence.EbeguPhysicalNamingStrategyImpl
                            </physicalNamingStrategy>
                            <!--verhindert, dass das Plugin versucht das schema physisch in eine DB zu schreiben-->
                            <execute>false</execute>
                            <format>true</format>
                            <!--File in welches das Schema exportiert wird (defaultist create.sql)-->
                            <outputFile>${project.build.directory}/ebegu-schema.ddl</outputFile>
                            <!--definiert ob der text fuer das sql-schema in die console geloggt wird-->
                            <show>true</show>
                            <detail>true</detail>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>org.mariadb.jdbc</groupId>
                                <artifactId>mariadb-java-client</artifactId>
                                <version>${version.mysqldriver}</version>
                            </dependency>
                            <!--   fuer die generierung wird jaxb gebraucht-->
                            <!--            JAXB modul einfuegen-->
                            <!-- Runtime -->
                            <dependency>
                                <groupId>jakarta.xml.bind</groupId>
                                <artifactId>jakarta.xml.bind-api</artifactId>
                                <version>${version.jakarata-xml}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.glassfish.jaxb</groupId>
                                <artifactId>jaxb-runtime</artifactId>
                                <version>${version.jaxb-runtime}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
