/*
 * Ki-Tax: System for the management of external childcare subsidies
 * Copyright (C) 2017 City of Bern Switzerland
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package ch.dvbern.ebegu.enums;

/**
 * Enum fuer den Dokumenten Typ
 */
public enum DokumentTyp {
	NACHWEIS_TRENNUNG, //mutation
	// FamSit
	NACHWEIS_UNTERHALTSVEREINBARUNG, FACHSTELLENBESTAETIGUNG, ABSAGESCHREIBEN_HORTPLATZ, NACHWEIS_ERWERBSPENSUM, NACHWEIS_ERWERBSPENSUM_UNREGELMAESSIG, NACHWEIS_SELBSTAENDIGKEIT, NACHWEIS_AUSBILDUNG, NACHWEIS_RAV, NACHWEIS_ARBEITSSUCHEND, NACHWEIS_FREIWILLIGENARBEIT, NACHWEIS_GESUNDHEITLICHE_INDIKATION, BESTAETIGUNG_ARZT, NACHWEIS_INTEGRATION_BESCHAEFTIGUNSPROGRAMM, STEUERVERANLAGUNG, NACHWEIS_ABGERECHNETE_QUELLENSTEUERN, STEUERERKLAERUNG, JAHRESLOHNAUSWEISE, NACHWEIS_SOZIALHILFE, NACHWEIS_BRUTTOLOHN, NACHWEIS_NETTOLOHN, NACHWEIS_FAMILIENZULAGEN, NACHWEIS_ERSATZEINKOMMEN, NACHWEIS_ERHALTENE_ALIMENTE, NACHWEIS_GELEISTETE_ALIMENTE, NACHWEIS_VERMOEGEN, NACHWEIS_SCHULDEN, ERFOLGSRECHNUNGEN_JAHR, ERFOLGSRECHNUNGEN_JAHR_MINUS1, ERFOLGSRECHNUNGEN_JAHR_MINUS2, NACHWEIS_ERSATZINKOMMEN_SELBSTSTAENDIGKEIT_JAHR, NACHWEIS_ERSATZINKOMMEN_SELBSTSTAENDIGKEIT_JAHR_MINUS1, NACHWEIS_ERSATZINKOMMEN_SELBSTSTAENDIGKEIT_JAHR_MINUS2, UNTERSTUETZUNGSBESTAETIGUNG, NACHWEIS_GETEILTE_OBHUT, NACHWEIS_EINKAEUFE_VORSORGE, NACHWEIS_ABZUEGE_LIEGENSCHAFT,
	//EKV
	DIV, ORIGINAL_PAPIERGESUCH, ORIGINAL_FREIGABEQUITTUNG, BESTAETIGUNG_AUSSERORDENTLICHER_BETREUUNGSAUFWAND, BESTAETIGUNG_KITA_PLUS, ERLAUTERUNG_ZUR_VERFUEGUNG, VORLAGE_MERKBLATT_TS, MERKBLATT_ANMELDUNG_TS, VORLAGE_VERFUEGUNG_LATS, VORLAGE_VERFUEGUNG_FERIENBETREUUNG, NACHWEIS_LOHNAUSWEIS_1, NACHWEIS_LOHNAUSWEIS_2, NACHWEIS_LOHNAUSWEIS_3, NACHWEIS_EINKOMMEN_VERFAHREN, NACHWEIS_BRUTTOVERMOEGENERTRAEGE, NACHWEIS_GEWINNUNGSKOSTEN, NACHWEIS_SCHULDZINSEN, NACHWEIS_NETTOERTRAEGE_ERBENGEMEINSCHAFTEN, AUSWEIS_ID, NACHWEIS_HOEHERE_BEITRAEGE_BEEINTRAECHTIGUNG;
}
