<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2023 DV Bern AG, Switzerland
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as
  ~ published by the Free Software Foundation, either version 3 of the
  ~ License, or (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program. If not, see <https://www.gnu.org/licenses />.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ebegu</artifactId>
        <groupId>ch.dvbern.ebegu</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ebegu-rest</artifactId>
    <packaging>war</packaging>

    <build>
        <plugins>
            <plugin>
                <executions>
                    <execution>
                        <id>node1</id>
                        <configuration>
                            <port>9990</port>
                        </configuration>
                    </execution>
                    <execution>
                        <id>node2</id>
                        <configuration>
                            <port>9991</port>
                        </configuration>
                    </execution>
                </executions>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>4.2.2.Final</version>
                <configuration>
                    <username>${wildfly-user}</username>
                    <password>${wildfly-pwd}</password>
                    <port>9090</port>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <warSourceDirectory>src/main/webapp</warSourceDirectory>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <dependencies>


        <!-- region WildFly Stack START -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-envers</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly.security.jakarta</groupId>
            <artifactId>jakarta-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-validator-provider</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.microprofile.health</groupId>
            <artifactId>microprofile-health-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.oss.healthcheck.gc</groupId>
            <artifactId>gc-health-check</artifactId>
        </dependency>
        <dependency>
            <!-- Fuer DB-Skripts (TransactionTimeout) -->
            <groupId>org.jboss.ejb3</groupId>
            <artifactId>jboss-ejb3-ext-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ejb</groupId>
            <artifactId>jakarta.ejb-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.batch</groupId>
            <artifactId>jakarta.batch-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>

        <!-- endregion WildFly Stack END --><!-- region submodules -->
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-external-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-server</artifactId>
            <version>${project.version}</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-dbschema</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-testutils</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.dvbern.ebegu</groupId>
            <artifactId>ebegu-auth</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- endregion -->

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jsonSchema-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
        </dependency>
        <dependency>
            <groupId>net.bull.javamelody</groupId>
            <artifactId>javamelody-core</artifactId>
        </dependency>
        <dependency>
            <groupId>net.java.dev.msv.datatype.xsd</groupId>
            <artifactId>xsdlib</artifactId>
            <version>20060615</version>
        </dependency>
        <dependency>
            <!-- OpenPDF instead of iText to add PDF export in JavaMelody -->
            <artifactId>openpdf</artifactId>
            <groupId>com.github.librepdf</groupId>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.microprofile.openapi</groupId>
            <artifactId>microprofile-openapi-api</artifactId>
        </dependency>

        <!-- region testing -->
        <dependency>
            <groupId>org.easymock</groupId>
            <artifactId>easymock</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- endregion -->

        <!--ClamAV-->
        <dependency>
            <groupId>io.github.microutils</groupId>
            <artifactId>kotlin-logging</artifactId>
            <version>1.12.5</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>xyz.capybara</groupId>
            <artifactId>clamav-client</artifactId>
            <version>2.0.2</version>
            <exclusions>
                <exclusion>
                    <groupId>io.github.microutils</groupId>
                    <artifactId>kotlin-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.wildfly.security</groupId>
            <artifactId>wildfly-elytron</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.security.enterprise</groupId>
            <artifactId>jakarta.security.enterprise-api</artifactId>
        </dependency>

        <!--endregion-->
    </dependencies>

    <profiles>
        <profile>
            <id>bootable-jar</id>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.wildfly.plugins</groupId>
                        <artifactId>wildfly-jar-maven-plugin</artifactId>
                        <version>10.0.0.Final</version>
                        <configuration>
                            <context-root>false</context-root>
                            <feature-packs>
                                <feature-pack>
                                    <location>org.wildfly:wildfly-galleon-pack:${version.wildfly.container}</location>
                                </feature-pack>
                                <feature-pack>
                                    <location>org.wildfly:wildfly-datasources-galleon-pack:3.0.0.Final</location>
                                </feature-pack>
                            </feature-packs>
                            <layers>
                                <layer>jaxrs-server</layer>
                                <layer>batch-jberet</layer>
                                <layer>elytron</layer>
                                <layer>observability</layer>
                                <layer>transactions</layer>
                                <layer>web-clustering</layer>
                                <layer>mariadb-datasource</layer>
                                <layer>microprofile-platform</layer>
                                <layer>elytron-oidc-client</layer>
                                <layer>ejb</layer>
                            </layers>
                            <arguments>--properties=/home/mobj/projects/kibon/kibon-app/ebegu-rest/ebegu-bootable-jar.properties</arguments>
                            <plugin-options>
                                <jboss-maven-dist>true</jboss-maven-dist>
                                <jboss-fork-embedded>true</jboss-fork-embedded>
                            </plugin-options>
                            <cli-sessions>
                                <cli-session>
                                    <script-files>
                                        <script>/home/mobj/projects/kibon/kibon-app/ebegu-rest/ebegu-customization.cli</script>
                                    </script-files>
                                </cli-session>
                            </cli-sessions>
                            <debug>true</debug>
                            <debug-suspend>true</debug-suspend>
                            <remote>true</remote>
                            <username>admin</username>
                            <password>admin</password>
                            <jvmArguments>
                                <argument>-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n</argument>
                            </jvmArguments>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local-cluster-deploy</id>
            <build>
                <plugins>
                    <plugin>
                        <executions>
                            <execution>
                                <id>node1</id>
                                <configuration>
                                    <port>9990</port>
                                </configuration>
                            </execution>
                            <execution>
                                <id>node2</id>
                                <configuration>
                                    <port>9991</port>
                                </configuration>
                            </execution>
                        </executions>
                        <groupId>org.wildfly.plugins</groupId>
                        <artifactId>wildfly-maven-plugin</artifactId>
                        <version>4.2.1.Final</version>
                        <configuration>
                            <username>${wildfly-user}</username>
                            <password>${wildfly-pwd}</password>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
